import { ArrowRight, CheckCircle2, Play, Sparkles } from 'lucide-react'
import { Link } from 'react-router-dom'
import { faculty, results, testimonials } from '../data/siteData'
import { CTASection, CourseCard, FAQAccordion, FacultyCard, StatsSection, TestimonialCard } from '../components/Common'
import { Button, SectionHeading } from '../components/Layout'
import { courses } from '../data/siteData'

export default function Home() { return <>
  <section className="hero"><div className="container hero-grid"><div className="hero-copy"><div className="pill"><Sparkles size={14} /> Admissions open for 2025–26</div><h1>Build your future with the <em>right guidance.</em></h1><p>At Apex, we turn potential into performance through expert teaching, personal mentorship and a plan built around you.</p><div className="hero-actions"><Button to="/courses">Explore courses</Button><Link to="/admission" className="text-link"><span className="play"><Play size={13} fill="currentColor" /></span> Enquire now</Link></div><div className="hero-proof"><div className="avatar-stack"><span>AM</span><span>NK</span><span>SB</span><span>+</span></div><span><strong>Trusted by 10,000+ families</strong><small>Across New Delhi and beyond</small></span></div></div><div className="hero-visual"><div className="hero-image"><img src="https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=1200&q=85" alt="Students collaborating in a bright classroom" /><div className="hero-caption"><span className="caption-icon">↗</span><span><strong>95.4%</strong><small>CBSE top score, 2025</small></span></div></div><div className="scribble">For the<br /><em>curious.</em></div></div></div></section>
  <StatsSection />
  <section className="section courses-preview"><div className="container"><SectionHeading eyebrow="Find your edge" title="Programs designed to move you forward." text="Focused programs. Brilliant teachers. A learning environment that makes hard things feel possible." /><div className="course-grid">{courses.slice(0, 3).map(course => <CourseCard course={course} key={course.id} />)}</div><div className="center-action"><Button to="/courses" variant="outline">View all courses</Button></div></div></section>
  <section className="section why-section"><div className="container split-grid"><div className="why-art"><img src="https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=1000&q=80" alt="Student studying at Apex Academy" /><span className="vertical-note">THE APEX APPROACH</span><div className="why-card"><strong>01</strong><p>We teach the<br /><em>why</em>, not just the what.</p></div></div><div className="why-copy"><SectionHeading eyebrow="Why Apex" title="The difference is in the details." text="Great outcomes are rarely accidental. They come from a learning system that sees the whole student." /><ul className="reason-list"><li><CheckCircle2 /><span><strong>Mentors, not just teachers</strong><small>One-on-one check-ins keep your progress visible and your goals close.</small></span></li><li><CheckCircle2 /><span><strong>A plan that adapts</strong><small>Regular diagnostics help us tune the pace, depth and support you need.</small></span></li><li><CheckCircle2 /><span><strong>Confidence by design</strong><small>Small wins, real feedback and a community that believes in your potential.</small></span></li></ul><Link to="/about" className="arrow-link">Discover our approach <ArrowRight size={17} /></Link></div></div></section>
  <section className="section faculty-preview"><div className="container"><SectionHeading eyebrow="Meet your mentors" title="Experience that meets you where you are." text="Our faculty bring deep expertise and a genuine investment in every student's journey." /><div className="faculty-grid">{faculty.slice(0, 3).map(person => <FacultyCard person={person} key={person.name} />)}</div></div></section>
  <section className="section testimonials-section"><div className="container"><SectionHeading eyebrow="The Apex effect" title="Don't take our word for it." /><div className="testimonial-grid">{testimonials.map(item => <TestimonialCard testimonial={item} key={item.name} />)}</div></div></section>
  <section className="section results-preview"><div className="container results-row"><div><SectionHeading eyebrow="Proof, not promises" title="When preparation meets purpose." text="Behind every number is a student who found the confidence to go further." /><Button to="/results" variant="outline">See all results</Button></div><div className="mini-results">{results.map(item => <div className={`mini-result ${item.color}`} key={item.student}><strong>{item.rank}</strong><span>{item.student}</span><small>{item.exam} · {item.score}</small></div>)}</div></div></section>
  <section className="section faq-section" id="faq"><div className="container split-grid faq-grid"><SectionHeading eyebrow="Questions, answered" title="Start with clarity." text="Everything you need to know before taking the next step." /><FAQAccordion /></div></section>
  <CTASection />
</> }
