import { useState } from 'react'
import { Link } from 'react-router-dom'
import { ArrowUpRight, Check, Clock3, ChevronDown, Quote, Star } from 'lucide-react'
import { courses, faqs, stats } from '../data/siteData'

export function StatsSection({ dark = false }) { return <section className={`stats-section ${dark ? 'dark' : ''}`}><div className="container stats-grid">{stats.map(([number, label]) => <div className="stat" key={label}><strong>{number}</strong><span>{label}</span></div>)}</div></section> }
export function CourseCard({ course }) { return <article className="course-card"><div className="course-image"><img src={course.image} alt="" /><span>{course.category}</span></div><div className="course-body"><div className="course-meta"><span><Clock3 size={14} /> {course.duration}</span><span>{course.target}</span></div><h3>{course.name}</h3><p>{course.description}</p><div className="course-foot"><strong>{course.fee}</strong><Link to={`/courses/${course.id}`} aria-label={`View details for ${course.name}`}><ArrowUpRight size={18} /></Link></div></div></article> }
export function FacultyCard({ person }) { return <article className="faculty-card"><div className="faculty-image"><img src={person.image} alt={person.name} /></div><div className="faculty-body"><div><h3>{person.name}</h3><span className="faculty-subject">{person.subject}</span></div><p>{person.bio}</p><small>{person.qualification} · {person.experience}</small></div></article> }
export function TestimonialCard({ testimonial }) { return <article className="testimonial"><Quote className="quote-icon" size={27} /><div className="stars">{[1, 2, 3, 4, 5].map((star) => <Star key={star} size={14} fill="currentColor" />)}</div><p>“{testimonial.quote}”</p><div className="person-line"><span className="initials">{testimonial.initials}</span><span><strong>{testimonial.name}</strong><small>{testimonial.detail}</small></span></div></article> }
export function FAQAccordion() { const [active, setActive] = useState(0); return <div className="faq-list">{faqs.map(([question, answer], index) => <div className={`faq-item ${active === index ? 'open' : ''}`} key={question}><button onClick={() => setActive(active === index ? -1 : index)} aria-expanded={active === index}><span>{question}</span><ChevronDown size={19} /></button>{active === index && <p>{answer}</p>}</div>)}</div> }
export function CTASection() { return <section className="cta-section"><div className="container cta-inner"><div><span className="eyebrow">Your next chapter starts here</span><h2>Ready to find your<br /><em>unfair advantage?</em></h2></div><Link to="/admission" className="button button-light">Book a counselling call <ArrowUpRight size={16} /></Link></div></section> }
export function CheckList({ items }) { return <ul className="check-list">{items.map(item => <li key={item}><Check size={16} />{item}</li>)}</ul> }
export function CourseStrip() { return <div className="course-strip">{courses.slice(0, 3).map(course => <Link to={`/courses/${course.id}`} key={course.id}><span>{course.category}</span><strong>{course.name}</strong><ArrowUpRight size={17} /></Link>)}</div> }
